-- Mission 1000 Families — current product opportunity and honest Step 2 follow-up
-- Run once on the live database after deploying the PHP files.
-- Safe to run repeatedly. The trigger key stays unchanged so existing logs remain intact.

UPDATE email_templates
SET
  name = 'Trigger: Step 2 Done — Next Steps',
  subject = '{{name}}, your next steps are ready',
  body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#f5f5f5;font-family:Arial,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f5f5;"><tr><td align="center" style="padding:20px 0;"><table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.1);"><tr><td><img src="https://simple2success.com/backoffice/app-assets/img/banner/newleademailheader.jpg" width="600" alt="Simple2Success" style="display:block;width:100%;max-width:600px;"></td></tr><tr><td style="padding:30px 40px;color:#333;font-size:15px;line-height:1.8;"><h2 style="color:#cb2ebc;margin-top:0;">Hi {{name}},</h2><p>Step 2 is complete. Your account setup is ready for the next phase.</p><p>Continue in order: Step 3 — choose your traffic, Step 4 — review your product options, then Step 5 — follow up and repeat what works.</p><p>There is also an optional current product conversation tool: the FitLine AI Scanner. Official partner information describes an app-based skin scan that evaluates more than 100 skin points and features and shows products matched to the customer profile. Check the current starter-set access, price and terms, and use the same Team Partner account for the purchase and the FitLine App sign-in.</p><p><a href="https://www.pm-international.com/de/de-de/partner/news/every-skin-is-different" style="color:#a51bc2;font-weight:bold;">View the official launch information &rarr;</a></p><p style="background:#f9f0ff;border-left:4px solid #cb2ebc;padding:12px 16px;border-radius:4px;"><strong>Choose one next action, review the result and keep your decisions in your control.</strong></p><div style="text-align:center;margin:28px 0;"><a href="{{cta_url}}" style="background:#cb2ebc;color:white;padding:14px 32px;border-radius:6px;text-decoration:none;font-weight:bold;font-size:15px;">Open Steps 3–5 &rarr;</a></div><p style="color:#888;font-size:13px;">Customer outcomes and income are not guaranteed.<br>Your Simple2Success Team</p></td></tr><tr><td style="background:#1a1a1a;padding:20px;text-align:center;color:#aaa;font-size:12px;">Copyright &copy; 2025 <a href="https://www.simple2success.com" style="color:#cb2ebc;text-decoration:none;">SIMPLE2SUCCESS</a>. All rights reserved.</td></tr></table></td></tr></table></body></html>'
WHERE template_key = 'trigger_step2_done_no_step4';
